version: "3.7"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - "POSTGRES_USER=postger"
      - "POSTGRES_PASSWORD=postger"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres-data: